#### Preamble
MACHINEOVERRIDES =. "${@['', 'scobc-v1-generic:']['scobc-v1-generic' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/versal-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' scobc_v1_generic']['scobc_v1_generic' != "${MACHINE}"]}"
